### ISSUE TITLE
Auto Complete Edittext is closing automatically ! whenever i press the idittext, the onError method calls again and again ! what am i doing wrong?

### ISSUE THREAD

**Issue by rohilla17** [pranaypatel512/PlaceAutocomplete#2]

**Comment by pranaypatel512** [comment]
You need to add your own **Google Map API key** in Manifest by adding your SHA on Google developer console. You also need to enable **Google Place API** too.
Please do it and provide you feedback.

Check https://developers.google.com/places/android-api/signup

**Comment by rohilla17** [comment]
Thanks!
